name: CLI action

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Install bat
        uses: ./.github/actions/my-cli-action
        with:
          version: '1.2.3'

      - name: Verify bat Installation
        run: |
          echo "Checking bat version..."
          batcat --version
